#!/usr/bin/env python

# ----------------------------------------------------------------------------
# Copyright (c) 2017-, labman development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

import click


@click.group()
def labman():
    pass


@labman.command()
@click.option('--port', required=False, type=int,
              help="Port where the webserver will start", default=8080)
def start_webserver(port):
    """Starts the labman webserver"""
    import socket
    import errno

    from tornado.httpserver import HTTPServer
    from tornado.ioloop import IOLoop

    from labman.gui.webserver import Application

    http_server = HTTPServer(Application())
    try:
        http_server.listen(port)
    except socket.error as e:
        if e.errno == errno.EADDRINUSE:
            raise RuntimeError(
                "Port %d is already in use. Please choose another "
                "port with --port" % port)
        else:
            raise

    click.echo("Labman started on port %d" % port)
    ioloop = IOLoop.instance()

    ioloop.start()


if __name__ == '__main__':
    labman()
